### ISSUE TITLE
Spawn enemies naturally

### ISSUE THREAD

**Issue by Deadrosas** [diogoabnunes/DDJD-FP#24]

**Comment by DiogoF17** [comment]
Como querem fazer esta cena do spawn?
Como querem que gere os inimigos? 
Em sitios aleatorios? 
Com alguma sequencia especifica?
Preciso de mais especifidade, se não não sei o que fazer.

**Comment by DiogoF17** [comment]
Mais info sobre o spawn:
Onde fazer?
Com que frequencia?
Quais inimigos?
...
Ta muito vago
